name: SAST Workflow for Php
permissions:
  contents: read
  checks: write
  id-token: write
on:
  push:
    branches:
      - main  # Adjust to your repository's default branch

jobs:
  sast:
    name: Run SAST Php checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # Adjust to your desired PHP version
          extensions: |
            pdo
            mbstring

      - name: Install dependencies
        run: composer install --no-progress --no-suggest

      - name: Run PHPStan
        run: vendor/bin/phpstan analyze login # Adjust the level as needed

